<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_speaker-program',
		'title' => 'Speaker Program',
		'fields' => array (
			array (
				'key' => 'field_5225023932d4d',
				'label' => 'Scribe',
				'name' => 'scribe',
				'type' => 'user',
				'instructions' => 'Select the scribe.',
				'required' => 1,
				'role' => array (
					0 => 'Scribe',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_527440d9a06b9',
				'label' => 'Editor',
				'name' => 'editor',
				'type' => 'user',
				'instructions' => 'Select the Editor',
				'required' => 1,
				'role' => array (
					0 => 'editor',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_5225000a8fdb2',
				'label' => 'Speaker First Name',
				'name' => 'speaker_first_name',
				'type' => 'text',
				'instructions' => 'Enter the speaker\'s first name',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52782ba22d4b0',
				'label' => 'Speaker Last Name',
				'name' => 'speaker_last_name',
				'type' => 'text',
				'instructions' => 'Enter the speaker\'s last name',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_522500598fdb3',
				'label' => 'Speaker Date',
				'name' => 'speaker_date',
				'type' => 'date_picker',
				'instructions' => 'Please select the date for the speaker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'M dd, yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_527440f4a06ba',
				'label' => 'Speaker Title',
				'name' => 'speaker_title',
				'type' => 'text',
				'instructions' => 'Enter the speaker title',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52744216acd41',
				'label' => 'Speaker Company',
				'name' => 'speaker_company',
				'type' => 'text',
				'instructions' => 'Enter the speaker\'s company',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_527441cd9d260',
				'label' => 'Speaker Email',
				'name' => 'speaker_email',
				'type' => 'email',
				'instructions' => 'Enter the speaker\'s email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_522501238fdb4',
				'label' => 'Speaker Program Content',
				'name' => 'speaker_program_content',
				'type' => 'wysiwyg',
				'instructions' => 'Add the speaker program details',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5225014c8fdb5',
				'label' => 'Speaker Program Images',
				'name' => 'speaker_program_images',
				'type' => 'repeater',
				'instructions' => 'Add the speaker program images',
				'sub_fields' => array (
					array (
						'key' => 'field_529e755f4501c',
						'label' => 'Speaker Program Image',
						'name' => 'speaker_program_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_52744275d7232',
				'label' => 'Speaker Program Notes',
				'name' => 'speaker_program_notes',
				'type' => 'wysiwyg',
				'instructions' => 'Enter the program notes following the talk.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_527442ab6e982',
				'label' => 'Speaker Bio',
				'name' => 'speaker_bio',
				'type' => 'textarea',
				'instructions' => 'Enter the Speaker Bio',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'rotary_speakers',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'format',
				2 => 'categories',
				3 => 'tags',
				4 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
?>